package com.yiling.stocktake.controller;

import com.yiling.stocktake.config.RequestAccessContext;
import com.yiling.stocktake.model.PageResponse;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/** 通用终端业务模块接口，承载医院供货、终端销量、整袋/零散/医院/期初库存及中药颗粒。 */
@RestController
@RequestMapping("/api/terminal")
public class GenericModuleController {
    private static final Set<String> MODULES = new HashSet<>(Arrays.asList("hospital-supply","terminal-sales","whole-inventory","loose-inventory","hospital-inventory","opening-inventory","herbal-granules"));
    private static final Set<String> SORTS = new HashSet<>(Arrays.asList("id","business_date","start_date","end_date","opening_date","hospital_name","material_code","drug_name","particle_qty","status","expiry_date","created_at"));
    private final JdbcTemplate jdbc;
    public GenericModuleController(JdbcTemplate jdbc) { this.jdbc = jdbc; }

    @GetMapping("/{module:hospital-supply|terminal-sales|whole-inventory|loose-inventory|hospital-inventory|opening-inventory|herbal-granules}")
    public PageResponse<Map<String,Object>> page(@PathVariable String module, @RequestParam Map<String,String> p, HttpServletRequest req) {
        check(module, req, "view");
        int page = integer(p.get("page"),1), size = Math.min(integer(p.get("pageSize"),20),200);
        List<Object> args = new ArrayList<>(); StringBuilder where = new StringBuilder(" module_code=? AND deleted_at IS NULL"); args.add(module);
        addLike(where,args,"hospital_name",p.get("hospitalName")); addLike(where,args,"material_code",p.get("materialCode")); addLike(where,args,"drug_name",p.get("drugName")); addLike(where,args,"batch_no",p.get("batchNo"));
        addEq(where,args,"hospital_id",p.get("hospitalId")); addEq(where,args,"status",p.get("status")); addEq(where,args,"validation_status",p.get("validationStatus"));
        addDate(where,args,"business_date",p.get("startDate"),p.get("endDate")); addDate(where,args,"expiry_date",p.get("expiryStart"),p.get("expiryEnd"));
        String order = SORTS.contains(p.get("sortField")) ? p.get("sortField") : "business_date"; String dir = "asc".equalsIgnoreCase(p.get("sortOrder")) ? "ASC" : "DESC";
        String base = " FROM module_business_record WHERE" + where;
        long total = jdbc.queryForObject("SELECT COUNT(*)"+base, args.toArray(), Long.class);
        List<Map<String,Object>> items = jdbc.queryForList("SELECT id,module_code AS moduleCode,business_date AS businessDate,start_date AS startDate,end_date AS endDate,opening_date AS openingDate,hospital_id AS hospitalId,hospital_name AS hospitalName,material_id AS materialId,material_code AS materialCode,particle_id AS particleId,batch_no AS batchNo,drug_name AS drugName,enterprise_name AS enterpriseName,national_name AS nationalName,spec_qty_per_bag AS specQtyPerBag,particle_qty AS particleQty,standard_particle_qty AS standardParticleQty,tablet_qty AS tabletQty,bag_count AS bagCount,particle_unit_price AS particleUnitPrice,currency,expiry_date AS expiryDate,status,validation_status AS validationStatus,lock_status AS lockStatus,source_type AS sourceType,extra_json AS extraJson,version_no AS versionNo,created_at AS createdAt,updated_at AS updatedAt"+base+" ORDER BY "+order+" "+dir+", id DESC LIMIT ? OFFSET ?", concat(args,size,(page-1)*size).toArray());
        Map<String,Object> summary = jdbc.queryForMap("SELECT COUNT(*) AS count, COALESCE(SUM(particle_qty),0) AS particleQty, COALESCE(SUM(standard_particle_qty),0) AS standardParticleQty, COALESCE(SUM(bag_count),0) AS bagCount, COALESCE(SUM(tablet_qty),0) AS tabletQty"+base,args.toArray());
        return new PageResponse<>(items,total,page,size,summary);
    }

    @GetMapping("/{module:hospital-supply|terminal-sales|whole-inventory|loose-inventory|hospital-inventory|opening-inventory|herbal-granules}/{id}")
    public Map<String,Object> detail(@PathVariable String module,@PathVariable long id,HttpServletRequest req) { check(module,req,"view"); Map<String,Object> item=jdbc.queryForMap("SELECT id,module_code AS moduleCode,business_date AS businessDate,start_date AS startDate,end_date AS endDate,opening_date AS openingDate,hospital_id AS hospitalId,hospital_name AS hospitalName,material_id AS materialId,material_code AS materialCode,particle_id AS particleId,batch_no AS batchNo,drug_name AS drugName,enterprise_name AS enterpriseName,national_name AS nationalName,spec_qty_per_bag AS specQtyPerBag,particle_qty AS particleQty,standard_particle_qty AS standardParticleQty,tablet_qty AS tabletQty,bag_count AS bagCount,particle_unit_price AS particleUnitPrice,currency,expiry_date AS expiryDate,status,validation_status AS validationStatus,lock_status AS lockStatus,source_type AS sourceType,extra_json AS extraJson,version_no AS versionNo,created_at AS createdAt,updated_at AS updatedAt FROM module_business_record WHERE id=? AND module_code=? AND deleted_at IS NULL",id,module); return Collections.singletonMap("item",item); }

    @PostMapping("/{module:hospital-supply|terminal-sales|whole-inventory|loose-inventory|hospital-inventory|opening-inventory|herbal-granules}")
    public Map<String,Object> create(@PathVariable String module,@RequestBody Map<String,Object> b,HttpServletRequest req) { check(module,req,"create"); String sql="INSERT INTO module_business_record (module_code,business_date,start_date,end_date,opening_date,hospital_id,hospital_name,material_id,material_code,particle_id,batch_no,drug_name,enterprise_name,national_name,spec_qty_per_bag,particle_qty,standard_particle_qty,tablet_qty,bag_count,particle_unit_price,currency,expiry_date,status,validation_status,lock_status,source_type,extra_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; Object[] v={module,date(b,"businessDate"),date(b,"startDate"),date(b,"endDate"),date(b,"openingDate"),num(b,"hospitalId"),str(b,"hospitalName"),num(b,"materialId"),str(b,"materialCode"),str(b,"particleId"),str(b,"batchNo"),str(b,"drugName"),str(b,"enterpriseName"),str(b,"nationalName"),num(b,"specQtyPerBag"),dec(b,"particleQty"),dec(b,"standardParticleQty"),dec(b,"tabletQty"),dec(b,"bagCount"),dec(b,"particleUnitPrice"),strOr(b,"currency","CNY"),date(b,"expiryDate"),strOr(b,"status","ACTIVE"),strOr(b,"validationStatus","VALID"),strOr(b,"lockStatus","UNLOCKED"),strOr(b,"sourceType","MANUAL"),str(b,"extraJson")}; jdbc.update(sql,v); return Collections.singletonMap("id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class)); }

    @PutMapping("/{module:hospital-supply|terminal-sales|whole-inventory|loose-inventory|hospital-inventory|opening-inventory|herbal-granules}/{id}")
    public Map<String,Object> update(@PathVariable String module,@PathVariable long id,@RequestBody Map<String,Object> b,HttpServletRequest req) { check(module,req,"update"); jdbc.update("UPDATE module_business_record SET business_date=?,start_date=?,end_date=?,opening_date=?,hospital_id=?,hospital_name=?,material_id=?,material_code=?,particle_id=?,batch_no=?,drug_name=?,enterprise_name=?,national_name=?,spec_qty_per_bag=?,particle_qty=?,standard_particle_qty=?,tablet_qty=?,bag_count=?,particle_unit_price=?,currency=?,expiry_date=?,status=?,validation_status=?,lock_status=?,extra_json=?,version_no=version_no+1 WHERE id=? AND module_code=? AND deleted_at IS NULL",date(b,"businessDate"),date(b,"startDate"),date(b,"endDate"),date(b,"openingDate"),num(b,"hospitalId"),str(b,"hospitalName"),num(b,"materialId"),str(b,"materialCode"),str(b,"particleId"),str(b,"batchNo"),str(b,"drugName"),str(b,"enterpriseName"),str(b,"nationalName"),num(b,"specQtyPerBag"),dec(b,"particleQty"),dec(b,"standardParticleQty"),dec(b,"tabletQty"),dec(b,"bagCount"),dec(b,"particleUnitPrice"),strOr(b,"currency","CNY"),date(b,"expiryDate"),strOr(b,"status","ACTIVE"),strOr(b,"validationStatus","VALID"),strOr(b,"lockStatus","UNLOCKED"),str(b,"extraJson"),id,module); return Collections.singletonMap("updated",true); }

    @DeleteMapping("/{module:hospital-supply|terminal-sales|whole-inventory|loose-inventory|hospital-inventory|opening-inventory|herbal-granules}")
    public Map<String,Object> remove(@PathVariable String module,@RequestBody Map<String,Object> b,HttpServletRequest req) { check(module,req,"delete"); List<?> ids=(List<?>)b.getOrDefault("ids",Collections.emptyList()); int n=0; for(Object x:ids) n+=jdbc.update("UPDATE module_business_record SET status='VOID',deleted_at=NOW() WHERE id=? AND module_code=? AND deleted_at IS NULL",Long.valueOf(String.valueOf(x)),module); return Collections.singletonMap("affectedCount",n); }

    @PostMapping("/{module}/validate") public Map<String,Object> validate(@PathVariable String module,@RequestBody Map<String,Object> b,HttpServletRequest req){check(module,req,"validate"); List<?> ids=(List<?>)b.getOrDefault("ids",Collections.emptyList()); int n=0; for(Object x:ids)n+=jdbc.update("UPDATE module_business_record SET validation_status='VALID' WHERE id=? AND module_code=? AND deleted_at IS NULL",Long.valueOf(String.valueOf(x)),module); return Collections.singletonMap("affectedCount",n);}
    @PostMapping("/{module}/aggregate") public Map<String,Object> aggregate(@PathVariable String module,@RequestBody Map<String,Object> b,HttpServletRequest req){check(module,req,"aggregate"); return Collections.singletonMap("successCount",jdbc.queryForObject("SELECT COUNT(*) FROM module_business_record WHERE module_code=? AND deleted_at IS NULL",Long.class));}
    @PostMapping("/{module}/export") public ResponseEntity<byte[]> export(@PathVariable String module,@RequestBody(required=false) Map<String,Object> b,HttpServletRequest req){check(module,req,"export"); Map<String,String> p=new HashMap<>(); if(b!=null&&b.get("query") instanceof Map){((Map<?,?>)b.get("query")).forEach((k,v)->{if(k!=null&&v!=null)p.put(String.valueOf(k),String.valueOf(v));});} List<Object> args=new ArrayList<>(); StringBuilder where=new StringBuilder(" module_code=? AND deleted_at IS NULL"); args.add(module); addLike(where,args,"hospital_name",p.get("hospitalName")); addLike(where,args,"material_code",p.get("materialCode")); addLike(where,args,"drug_name",p.get("drugName")); addLike(where,args,"batch_no",p.get("batchNo")); addEq(where,args,"hospital_id",p.get("hospitalId")); addEq(where,args,"status",p.get("status")); addDate(where,args,"business_date",p.get("startDate"),p.get("endDate")); List<Map<String,Object>> rows=jdbc.queryForList("SELECT id,business_date,hospital_name,material_code,drug_name,particle_qty,standard_particle_qty,bag_count,status,validation_status FROM module_business_record WHERE"+where+" ORDER BY business_date DESC,id DESC LIMIT 50000",args.toArray()); StringBuilder s=new StringBuilder("ID,日期,医院,物料编码,药品名称,颗粒量,标准颗粒量,袋数,状态,校验状态\n"); for(Map<String,Object> r:rows){s.append(Arrays.stream(new Object[]{r.get("id"),r.get("business_date"),r.get("hospital_name"),r.get("material_code"),r.get("drug_name"),r.get("particle_qty"),r.get("standard_particle_qty"),r.get("bag_count"),r.get("status"),r.get("validation_status")}).map(x->"\""+(x==null?"":String.valueOf(x).replace("\"","\"\""))+"\"").collect(Collectors.joining(","))).append('\n');} byte[] bytes=s.toString().getBytes(StandardCharsets.UTF_8); byte[] bom={(byte)0xEF,(byte)0xBB,(byte)0xBF}; byte[] out=new byte[bom.length+bytes.length]; System.arraycopy(bom,0,out,0,bom.length); System.arraycopy(bytes,0,out,bom.length,bytes.length); return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename="+module+".csv").contentType(MediaType.parseMediaType("text/csv;charset=UTF-8")).body(out); }

    @PostMapping("/{module}/import") public Map<String,Object> importRows(@PathVariable String module,@RequestBody Map<String,Object> body,HttpServletRequest req){check(module,req,"import"); Object raw=body==null?null:body.get("items"); if(!(raw instanceof List)) throw new IllegalArgumentException("items 必须是数组"); int n=0; for(Object item:(List<?>)raw){if(!(item instanceof Map)) continue; Map<String,Object>b=(Map<String,Object>)item; if(str(b,"materialCode")==null||str(b,"materialCode").trim().isEmpty()) continue; String sql="INSERT INTO module_business_record (module_code,business_date,start_date,end_date,opening_date,hospital_id,hospital_name,material_id,material_code,particle_id,batch_no,drug_name,particle_qty,standard_particle_qty,tablet_qty,bag_count,particle_unit_price,expiry_date,status,validation_status,lock_status,source_type,extra_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; jdbc.update(sql,module,date(b,"businessDate"),date(b,"startDate"),date(b,"endDate"),date(b,"openingDate"),num(b,"hospitalId"),str(b,"hospitalName"),num(b,"materialId"),str(b,"materialCode"),str(b,"particleId"),str(b,"batchNo"),str(b,"drugName"),dec(b,"particleQty"),dec(b,"standardParticleQty"),dec(b,"tabletQty"),dec(b,"bagCount"),dec(b,"particleUnitPrice"),date(b,"expiryDate"),strOr(b,"status","ACTIVE"),strOr(b,"validationStatus","VALID"),strOr(b,"lockStatus","UNLOCKED"),strOr(b,"sourceType","IMPORT"),str(b,"extraJson")); n++;} return Collections.singletonMap("importedCount",n); }
    @PostMapping("/{module}/lock") public Map<String,Object> lock(@PathVariable String module,@RequestBody Map<String,Object>b,HttpServletRequest req){check(module,req,"lock"); List<?>ids=(List<?>)b.getOrDefault("ids",Collections.emptyList()); String state=Boolean.FALSE.equals(b.get("locked"))?"UNLOCKED":"LOCKED"; int n=0; for(Object x:ids)n+=jdbc.update("UPDATE module_business_record SET lock_status=? WHERE id=? AND module_code=? AND deleted_at IS NULL",state,Long.valueOf(String.valueOf(x)),module); return Collections.singletonMap("affectedCount",n);}

    private void check(String module,HttpServletRequest req,String op){if(!MODULES.contains(module)) throw new IllegalArgumentException("未知模块"); RequestAccessContext.require(req,"terminal:"+module+":"+op);}
    private static int integer(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}} private static Object num(Map<String,Object>b,String k){Object v=b.get(k);if(v==null||String.valueOf(v).isEmpty())return null;try{return Long.valueOf(String.valueOf(v));}catch(Exception e){return null;}} private static BigDecimal dec(Map<String,Object>b,String k){Object v=b.get(k);if(v==null||String.valueOf(v).isEmpty())return null;try{return new BigDecimal(String.valueOf(v));}catch(Exception e){return null;}} private static String str(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:String.valueOf(v);} private static String strOr(Map<String,Object>b,String k,String d){String s=str(b,k);return s==null||s.isEmpty()?d:s;} private static java.sql.Date date(Map<String,Object>b,String k){String s=str(b,k);try{return s==null||s.isEmpty()?null:java.sql.Date.valueOf(LocalDate.parse(s));}catch(Exception e){return null;}}
    private static void addLike(StringBuilder w,List<Object>a,String c,String v){if(v!=null&&!v.trim().isEmpty()){w.append(" AND ").append(c).append(" LIKE ?");a.add("%"+v.trim()+"%");}} private static void addEq(StringBuilder w,List<Object>a,String c,String v){if(v!=null&&!v.trim().isEmpty()){w.append(" AND ").append(c).append("=?");a.add(v);}} private static void addDate(StringBuilder w,List<Object>a,String c,String f,String t){if(f!=null&&!f.isEmpty()){w.append(" AND ").append(c+">= ?");a.add(f);}if(t!=null&&!t.isEmpty()){w.append(" AND ").append(c+"<= ?");a.add(t);}} private static List<Object> concat(List<Object>a,Object...x){List<Object>r=new ArrayList<>(a);r.addAll(Arrays.asList(x));return r;}
}
