package com.yiling.stocktake.controller;

import com.yiling.stocktake.config.RequestAccessContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import javax.servlet.http.HttpServletRequest;
import java.util.*;

@RestController
@RequestMapping("/api/terminal/hospitals")
public class HospitalController {
  private final JdbcTemplate jdbc;
  public HospitalController(JdbcTemplate jdbc){this.jdbc=jdbc;}
  @GetMapping public List<Map<String,Object>> tree(@RequestParam(required=false) String keyword,@RequestParam(required=false) String status,@RequestParam(required=false) String categoryCode,HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:view"); StringBuilder w=new StringBuilder(" WHERE 1=1 "); List<Object>a=new ArrayList<>(); if(keyword!=null&&!keyword.trim().isEmpty()){w.append(" AND (hospital_name LIKE ? OR hospital_code LIKE ?)");a.add("%"+keyword.trim()+"%");a.add("%"+keyword.trim()+"%");} if(status!=null&&!status.isEmpty()){w.append(" AND status=?");a.add(status);}if(categoryCode!=null&&!categoryCode.isEmpty()){w.append(" AND category_code=?");a.add(categoryCode);} List<Map<String,Object>> all=jdbc.queryForList("SELECT id,parent_id AS parentId,path,level_no AS level,name AS name,hospital_name AS hospitalName,category_code AS categoryCode,sort_order AS sortOrder,owner_name AS ownerName,owner_phone AS ownerPhone,hospital_code AS hospitalCode,status FROM hospital"+w+" ORDER BY level_no,sort_order,id",a.toArray()); return all; }
  @GetMapping("/{id}") public Map<String,Object> detail(@PathVariable long id,HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:view");return jdbc.queryForMap("SELECT id,parent_id AS parentId,path,level_no AS level,name,hospital_name AS hospitalName,category_code AS categoryCode,sort_order AS sortOrder,owner_name AS ownerName,owner_phone AS ownerPhone,hospital_code AS hospitalCode,status,version_no AS version FROM hospital WHERE id=?",id);}
  @PostMapping public Map<String,Object> create(@RequestBody Map<String,Object>b,HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:create"); Long parent=longVal(b.get("parentId")); String name=str(b,"name",str(b,"hospitalName",null)); jdbc.update("INSERT INTO hospital(parent_id,path,level_no,hospital_name,name,category_code,sort_order,owner_name,owner_phone,hospital_code,status) VALUES(?,?,1,?,?,?,?,?,?,?,?)",parent,null,name,name,str(b,"categoryCode",null),num(b.get("sortOrder")),str(b,"ownerName",null),str(b,"ownerPhone",null),str(b,"hospitalCode",null),str(b,"status","ACTIVE")); Long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class); jdbc.update("UPDATE hospital SET level_no=CASE WHEN parent_id IS NULL THEN 1 ELSE COALESCE((SELECT level_no+1 FROM (SELECT level_no FROM hospital WHERE id=?)x),2) END, path=CONCAT(COALESCE((SELECT path FROM (SELECT path FROM hospital WHERE id=?)x),''),CASE WHEN parent_id IS NULL THEN '' ELSE CONCAT('/',parent_id) END,'/',id) WHERE id=?",parent,parent,id); return Collections.singletonMap("id",id);}
  @PutMapping("/{id}") public Map<String,Object> update(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:update"); jdbc.update("UPDATE hospital SET hospital_name=?,name=?,category_code=?,sort_order=?,owner_name=?,owner_phone=?,hospital_code=?,status=?,updated_at=NOW() WHERE id=?",str(b,"name",str(b,"hospitalName",null)),str(b,"name",str(b,"hospitalName",null)),str(b,"categoryCode",null),num(b.get("sortOrder")),str(b,"ownerName",null),str(b,"ownerPhone",null),str(b,"hospitalCode",null),str(b,"status","ACTIVE"),id); return Collections.singletonMap("updated",true);}
  @DeleteMapping("/{id}") public Map<String,Object> disable(@PathVariable long id,HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:delete"); jdbc.update("UPDATE hospital SET status='INACTIVE',updated_at=NOW() WHERE id=?",id); return Collections.singletonMap("updated",true);}
  @GetMapping("/categories") public List<Map<String,Object>> categories(HttpServletRequest req){RequestAccessContext.require(req,"terminal:hospitals:view");return jdbc.queryForList("SELECT category_code AS categoryCode,category_name AS categoryName,sort_order AS sortOrder FROM hospital_category WHERE status='ACTIVE' ORDER BY sort_order,id");}
  private static String str(Map<String,Object>b,String k,String d){Object v=b.get(k);return v==null?d:String.valueOf(v);} private static Long longVal(Object v){try{return v==null?null:Long.valueOf(String.valueOf(v));}catch(Exception e){return null;}} private static Integer num(Object v){try{return v==null?0:Integer.valueOf(String.valueOf(v));}catch(Exception e){return 0;}}
}
